const fs=require('fs'),path=require('path'),http=require('http'),cp=require('child_process'),crypto=require('crypto');
const base=process.env.EVIDENCE_DIR,web=process.env.QUAL_WEB,node=process.execPath;const {chromium}=require(process.env.PLAYWRIGHT_MODULE);const routes=['/','/privacy','/login','/signup','/pricing','/opensource','/auth/google/callback'];const fp=v=>v?crypto.createHash('sha256').update(v).digest('hex'):null;const redact=s=>s.replace(/'nonce-([^']+)'/g,"'nonce-REDACTED'");
const env={PATH:path.dirname(node)+':/usr/bin:/bin',HOME:base,TMPDIR:base,NODE_ENV:'production',NEXT_TELEMETRY_DISABLED:'1',NEXT_PUBLIC_API_URL:'https://api.xpertapply.com',NEXT_PUBLIC_SITE_URL:'https://xpertapply.com',NEXT_PUBLIC_CHROME_EXTENSION_ID:'gnibjomjfdobadlockphjiibbpmiehcj'};let server,proxy,mode='normal',controlUsed=false,stalePolicy;const results=[];
const dashboardSummary={freshMatches:4,applications:{saved:2,inProgress:1,interviews:1,offers:0},recentApplications:[],topMatches:[],strongMatches:2,nextAction:{kind:'discover',eyebrow:'Next step',title:'Find your next role',body:'Review the latest jobs selected for your search.',href:'/jobs',cta:'Browse jobs',firstName:'Taylor',profileProgress:80}};
async function start(){}
async function stop(){}
(async()=>{proxy=http.createServer((req,res)=>{const q=http.request({hostname:'127.0.0.1',port:3551,path:req.url,method:req.method,headers:req.headers},r=>{const hs={...r.headers};if(['wrong','stale'].includes(mode)&&!controlUsed&&req.url==='/'){controlUsed=true;const actual=hs['content-security-policy'];hs['content-security-policy']=mode==='wrong'?actual.replace(/'nonce-[^']+'/g,"'nonce-"+crypto.randomBytes(16).toString('base64')+"'"):stalePolicy;}if(mode==='style'&&!controlUsed&&req.url==='/'){controlUsed=true;const chunks=[];r.on('data',d=>chunks.push(d));r.on('end',()=>{let body=Buffer.concat(chunks).toString();body=body.replace('</head>','<style>'+fs.readFileSync(web+'/public/csp-error.css','utf8')+'</style></head>').replace('</body>','<div class="wrap" id="style-control-probe">Style control</div></body>');delete hs['content-length'];res.writeHead(r.statusCode,hs);res.end(body)});}else{res.writeHead(r.statusCode,hs);r.pipe(res)}});q.on('error',()=>{res.writeHead(502);res.end('local upstream unavailable')});req.pipe(q)});await new Promise(r=>proxy.listen(3552,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
async function observe(build,viewport,label,full,auth=false,extraHeaders={}){const record={build,viewport,label,authFixture:auth,events:[],console:[],pageerrors:[],failed:[],responses:[],documents:[],snapshots:[],interactions:[]};results.push(record);let scenario='';const c=await browser.newContext({viewport:viewport==='desktop'?{width:1440,height:1000}:{width:390,height:844},extraHTTPHeaders:extraHeaders});
if(auth)await c.addInitScript(()=>localStorage.setItem('jobpilot_token','responsive-shell-token'));
await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='127.0.0.1')return r.continue();if(u.origin==='https://api.xpertapply.com'){let body;if(u.pathname==='/auth/providers')body={google:{enabled:false}};else if(auth&&u.pathname==='/dashboard/summary')body=dashboardSummary;else if(auth){if(r.request().method()!=='GET'){record.failed.push({scenario,url:u.pathname,reason:'fixture mutation prohibited'});return r.abort();}body={};if(u.pathname==='/profile')body={profile:{full_name:'Taylor Example',email:'taylor@example.test',location:'New York, NY'}};else if(u.pathname==='/jobs')body={profile_complete:true,criteria:{role_queries:[],skills:[],seniority_targets:[]},profile_filters:{target_roles:[],target_levels:[],preferred_locations:[],work_preference:'remote'},jobs:[]};else if(u.pathname.startsWith('/jobs/tracker/'))body={applications:[]};else if(u.pathname==='/profile/career')body={education:[],experience:[],projects:[],certifications:[],awards:[],publications:[]};else if(u.pathname==='/profile/completeness'){const score={percent:60,satisfied:[],missing:[]};body={completion:score,autofillReadiness:score};}else if(u.pathname==='/profile/demographics')body={demographics:null};else if(u.pathname==='/profile/application-eligibility')body={answers:[]};}if(body)return r.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(body)});}record.failed.push({scenario,url:u.origin+u.pathname,reason:'unapproved external request prevented'});return r.abort();});
await c.exposeBinding('__nonceEvent',(_,e)=>record.events.push({scenario,...e,originalPolicy:redact(e.originalPolicy),policyNonceFingerprint:fp(e.originalPolicy.match(/'nonce-([^']+)'/)?.[1])}));await c.addInitScript(()=>{window.__docMarker=Math.random().toString(36);window.addEventListener('securitypolicyviolation',e=>window.__nonceEvent({documentURI:e.documentURI,blockedURI:e.blockedURI,effectiveDirective:e.effectiveDirective,violatedDirective:e.violatedDirective,originalPolicy:e.originalPolicy,sourceFile:e.sourceFile,lineNumber:e.lineNumber,columnNumber:e.columnNumber,sample:undefined,disposition:e.disposition,statusCode:e.statusCode}));});
const p=await c.newPage();p.on('console',m=>record.console.push({scenario,type:m.type(),text:redact(m.text())}));p.on('pageerror',e=>record.pageerrors.push({scenario,message:e.message}));p.on('requestfailed',r=>record.failed.push({scenario,url:r.url(),reason:r.failure()?.errorText,type:r.resourceType()}));p.on('response',r=>record.responses.push({scenario,url:r.url(),status:r.status(),type:r.request().resourceType(),contentType:r.headers()['content-type'],cacheControl:r.headers()['cache-control'],isRSC:r.request().headers()['rsc']==='1'}));
async function document(name,action){scenario=name;const r=await action();let nonce=null;if(r){const headers=await r.headersArray(),cs=headers.filter(h=>h.name.toLowerCase()==='content-security-policy');nonce=cs[0]?.value.match(/'nonce-([^']+)'/)?.[1];record.documents.push({scenario,url:r.url(),status:r.status(),cacheControl:r.headers()['cache-control'],cspCount:cs.length,reportOnlyCount:headers.filter(h=>h.name.toLowerCase()==='content-security-policy-report-only').length,nonceFingerprint:fp(nonce),policyTemplate:cs[0]?redact(cs[0].value):null});}await p.waitForLoadState('networkidle',{timeout:10000}).catch(()=>{});const snap=await p.evaluate(()=>({url:location.href,inline:[...document.scripts].filter(s=>!s.src).map(s=>({type:s.type,nonce:s.nonce,bytes:new TextEncoder().encode(s.textContent).length})),reactAttached:[...document.querySelectorAll('a,button,form')].filter(e=>Object.keys(e).some(k=>k.startsWith('__reactFiber$'))).length,bootstrap:Array.isArray(window.__next_f),docMarker:window.__docMarker,styleAttributes:document.querySelectorAll('[style]').length,styles:[...document.querySelectorAll('style')].map(s=>({nonce:s.nonce,text:s.textContent})),stylesheetLinks:[...document.querySelectorAll('link[rel="stylesheet"]')].map(s=>({href:s.href,loaded:[...document.styleSheets].some(x=>x.href===s.href)})),h1:document.querySelector('h1')?.textContent,htmlOverflow:document.documentElement.scrollWidth>innerWidth,cardRadius:document.querySelector('.card')?getComputedStyle(document.querySelector('.card')).borderRadius:null,styleControlDisplay:document.querySelector('#style-control-probe')?getComputedStyle(document.querySelector('#style-control-probe')).display:null}));snap.styles=snap.styles.map(s=>({nonceFingerprint:fp(s.nonce),sha256:crypto.createHash('sha256').update(s.text).digest('base64'),bytes:Buffer.byteLength(s.text)}));snap.inline=snap.inline.map(s=>({...s,nonceFingerprint:fp(s.nonce),matchesHeader:nonce?s.nonce===nonce:null,nonce:undefined}));record.snapshots.push({scenario,...snap});fs.writeFileSync(base+'/functional-smoke.json',JSON.stringify(results,null,2));}
if(label==='root-error'){
 await document('root-error',()=>p.goto('http://127.0.0.1:3552/'));await p.getByRole('heading',{name:'XpertApply could not load'}).waitFor();if(record.snapshots.at(-1).cardRadius!=='16px')throw Error('standalone global CSS unavailable');await p.screenshot({path:base+'/global-error-'+build+'-'+viewport+'.png',fullPage:true});
 await c.setExtraHTTPHeaders({});await p.getByRole('button',{name:'Reload',exact:true}).click();await p.getByRole('heading',{name:'XpertApply could not load'}).waitFor({state:'hidden'});await document('global-reset-restored',()=>p.goto('http://127.0.0.1:3552/'));record.interactions.push('global reset and fresh document restored');
}
else if(label==='segment-error'){
 await document('segment-error',()=>p.goto('http://127.0.0.1:3552/csp-qualification-error'));await p.getByRole('heading',{name:'Something went wrong'}).waitFor();await p.screenshot({path:base+'/segment-error-'+build+'-'+viewport+'.png'});await c.setExtraHTTPHeaders({});await p.getByRole('button',{name:'Try again',exact:true}).click();await p.getByRole('heading',{name:'Qualification segment recovered'}).waitFor();record.interactions.push('segment reset restored');await document('segment-reset-snapshot',async()=>null);
}
else if(auth){await document('auth-dashboard',()=>p.goto('http://127.0.0.1:3552/dashboard'));await p.getByRole('heading',{name:'Find your next role',exact:true}).waitFor();if(viewport==='mobile'){await p.getByRole('button',{name:'Open navigation',exact:true}).click();await p.keyboard.press('Escape');}else{await p.getByRole('button',{name:'Collapse sidebar',exact:true}).click();await p.getByRole('button',{name:'Expand sidebar',exact:true}).click();}record.interactions.push('authenticated shell responsive controls');}
else if(label==='guard'){
for(const route of ['/dashboard']){await document('guard-'+route,()=>p.goto('http://127.0.0.1:3552'+route));await p.waitForURL(u=>u.pathname==='/login');await p.getByRole('heading',{name:'Sign in to XpertApply'}).waitFor();await document('guard-final-'+route,async()=>null);record.interactions.push({scenario:'guard-'+route,destination:p.url()});}
}
else {await document('cold',()=>p.goto('http://127.0.0.1:3552/'));
if(full){
if(viewport==='mobile'){await p.getByRole('button',{name:'Open menu',exact:true}).click();await p.locator('#xa-mobile-menu').waitFor();record.interactions.push('mobile menu opens');await p.keyboard.press('Escape');await p.locator('#xa-mobile-menu').waitFor({state:'hidden'});record.interactions.push('mobile menu Escape closes');await p.getByRole('button',{name:'Open menu',exact:true}).click();await p.locator('#xa-mobile-menu').getByRole('button',{name:'Pricing',exact:true}).click();}else await p.getByRole('button',{name:'Pricing',exact:true}).first().click();await p.getByRole('dialog').waitFor();record.interactions.push('pricing opens');await p.keyboard.press('Escape');await p.getByRole('dialog').waitFor({state:'hidden'});record.interactions.push('pricing closes');await document('landing-reload',()=>p.reload());
for(const route of routes.filter(r=>r!=='/')){await document('direct-'+route,()=>p.goto('http://127.0.0.1:3552'+route));await document('reload-'+route,()=>p.reload());if(['/login','/signup'].includes(route)){await p.getByRole('button',{name:'Show password',exact:true}).click();await p.getByRole('button',{name:'Hide password',exact:true}).waitFor();record.interactions.push(route+' password visibility works');await p.getByRole('button',{name:'Hide password',exact:true}).click();}if(route.endsWith('callback')){await p.locator('#google-link-error').waitFor();record.interactions.push('callback missing-code effect rendered');}
const home=p.locator('a[href="/"]:visible').first();if(await home.count()){scenario='client-home-'+route;const marker=await p.evaluate(()=>window.__docMarker);await home.click();await p.waitForURL(u=>u.pathname==='/');record.interactions.push({scenario,sameDocument:marker===await p.evaluate(()=>window.__docMarker)});await document(scenario,async()=>null);await p.goBack();await p.waitForURL(u=>u.pathname===route);record.interactions.push({scenario:'back-'+route,sameDocument:marker===await p.evaluate(()=>window.__docMarker)});}}
await document('return-landing',()=>p.goto('http://127.0.0.1:3552/'));if(viewport==='mobile')await p.getByRole('button',{name:'Open menu',exact:true}).click();const marker=await p.evaluate(()=>window.__docMarker);scenario='client-login';await p.locator('a[href="/login"]:visible').first().click();await p.waitForURL(u=>u.pathname==='/login');record.interactions.push({scenario,sameDocument:marker===await p.evaluate(()=>window.__docMarker)});await p.getByRole('button',{name:'Show password',exact:true}).click();await p.getByRole('button',{name:'Hide password',exact:true}).waitFor();
await document('application-not-found',()=>p.goto('http://127.0.0.1:3552/this-route-must-not-exist-csp-test'));await p.getByRole('heading',{name:'Page not found',exact:true}).waitFor();if(record.documents.at(-1).status!==404)throw Error('404 status');

}}
await c.close();fs.writeFileSync(base+'/functional-smoke.json',JSON.stringify(results,null,2));console.log(JSON.stringify({build,viewport,label,cspEvents:record.events.length,pageerrors:record.pageerrors.length,failed:record.failed.length}));}
for(const build of ['container']){await start(build);mode='normal';for(const viewport of ['desktop','mobile']){await observe(build,viewport,'public-regression',true);await observe(build,viewport,'auth-fixture',false,true);await observe(build,viewport,'guard',false);await observe(build,viewport,'segment-error',false,false,{'x-csp-qual-segment-error':'1'});await observe(build,viewport,'root-error',false,false,{'x-csp-qual-root-error':'1'});}await stop();}
await browser.close();await new Promise(r=>proxy.close(r));
})().catch(async e=>{fs.writeFileSync(base+'/regression-error.txt',e.stack);fs.writeFileSync(base+'/regression-partial.json',JSON.stringify(results,null,2));console.error(e);await stop();if(proxy)proxy.close();process.exit(1)});
