import Link from "next/link";

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 leading-7 sm:py-20">
      <Link href="/" className="ds-focus-ring rounded-control text-sm text-foreground-link underline underline-offset-4">XpertApply home</Link>
      <article className="mt-8 space-y-8 [&_h2]:mb-3 [&_h2]:text-2xl [&_h2]:font-semibold [&_p+p]:mt-3 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6">
        <header><h1 className="text-4xl font-semibold tracking-tight">Privacy policy</h1><p className="mt-3 text-sm text-[var(--text-muted)]">Last updated September 19, 2026</p></header>
        <section aria-labelledby="scope"><h2 id="scope">Scope and purpose</h2><p>This policy covers the XpertApply web app and Chrome extension. XpertApply helps you prepare, fill, and track job applications using information you provide and information from job and application pages you choose to use with XpertApply. You review and submit applications yourself.</p></section>
        <section aria-labelledby="information"><h2 id="information">Information you provide</h2><p>When you create an account, we process account identifiers such as your name, email address, internal user ID, and authentication or session information. Your profile may include contact details, work history, education, skills, preferences, professional links, work authorization and sponsorship answers, and answers you save for applications. Optional demographic information is handled separately from matching and resume generation.</p><p>If you choose to save a Workday application password, XpertApply stores it encrypted on the service. For a Workday application session, the service can send the password to the extension to fill the relevant account-creation fields on that application site. You can remove the saved password in your profile. The stored credential is excluded from AI processing.</p><p>You may upload a resume and create resumes, cover letters, application answers, and exports. We process the source material, generated content, document snapshots and provenance needed to prepare and manage those documents. You may also save jobs, employers, job URLs, application statuses, tracker history, prepared answers, confirmation state, and application sessions.</p></section>
        <section aria-labelledby="pages"><h2 id="pages">Application pages and browser activity</h2><p>When you start an application workflow, the extension may request access to that employer or application site, including a site reached through an application redirect or embedded form. With access, it reads relevant page and form information such as the page URL, form labels, questions, options, field state, and application context to identify fields, prepare assistance, and fill information you have provided or confirmed. Relevant information may be sent to the XpertApply service for requested application features, including answer preparation. Job and application URLs and related workflow records may be saved in your account.</p><p>When you choose to fill an employer or application form, the information placed in that form is available to that site and its application provider under their own practices. You review and submit the final application yourself.</p><p>The extension uses tab and navigation information to keep the selected application workflow bound to the correct page, including necessary redirects and new tabs. This is application-workflow activity; the feature does not require a general browser-history feed or monitoring unrelated tabs. You can decline or revoke an employer-site permission through Chrome, although filling on that site will then be unavailable.</p></section>
        <section aria-labelledby="storage"><h2 id="storage">Extension storage</h2><p>The extension uses Chrome session storage for temporary application handoffs, tab bindings, prepared packages, answers and progress, including session-sensitive information. Session storage survives service-worker suspension but is cleared when the browser restarts or the extension reloads; workflow state is also cleared when sessions end or account authority changes. Chrome local storage holds limited configuration and sanitized runtime or identity metadata. The extension does not use Chrome sync storage. Chrome manages the site permissions you grant.</p></section>
        <section aria-labelledby="uses"><h2 id="uses">How information is used and shared</h2><p>We use this information to authenticate your account; maintain your profile, documents and application tracker; prepare and assist with applications; discover professional contacts when you ask; and operate, secure and troubleshoot these features. Information is sent to the XpertApply service as needed for these actions.</p><ul><li><strong>OpenAI</strong> processes relevant profile, career, job, document, question, answer or outreach context for requested AI-assisted features such as profile import, resume, cover-letter and application-answer generation, and optional outreach improvement. Stored Workday credential ciphertext and credential-shaped keys are excluded from AI payloads.</li><li><strong>People Data Labs</strong> and <strong>Apollo</strong> may receive employer and professional search criteria, such as company domain, role, seniority and location, for user-requested recruiter or professional-contact discovery. Apollo may also receive provider person identifiers.</li><li><strong>Hunter</strong> may receive professional names, employer domains and discovered work email addresses for user-requested professional-email discovery or verification.</li><li><strong>Hostinger</strong> provides hosting infrastructure for the XpertApply service.</li></ul><p>Professional-contact providers are used for that requested feature, not for every ordinary application workflow. We do not promise that third-party providers retain or delete data on XpertApply&apos;s schedule.</p></section>
        <section aria-labelledby="retention"><h2 id="retention">Retention and deletion</h2><p>Account and profile information, saved applications and documents remain available while you use the account unless you edit or delete them or a specific lifecycle rule applies. Rejected and withdrawn application trackers are scheduled for deletion after a seven-day grace period; you can undo that scheduled deletion. Related application sessions are cleaned up with that lifecycle. Other application statuses have no universal seven-day deletion rule.</p><p>You can use the web app&apos;s privacy controls to export account data or delete your account. Account deletion removes account-owned database records and XpertApply-controlled materialized generated-document files. Editing, deleting or re-exporting a generated document also removes superseded files under XpertApply&apos;s control. These statements do not set a deletion schedule for third-party processors or for copies you have downloaded or submitted to employers.</p></section>
        <section aria-labelledby="controls"><h2 id="controls">Your controls and security</h2><p>You can review and edit profile information and application answers, manage documents and trackers, export your data, delete your account, and manage Chrome site access. The extension does not submit an employer application for you. XpertApply uses access controls and secure connections for its service and limits application-page access to the selected workflow. No internet service can guarantee absolute security.</p></section>
        <section aria-labelledby="limited-use"><h2 id="limited-use">Chrome Web Store Limited Use</h2><p>The use of information received from Google APIs will adhere to the Chrome Web Store User Data Policy, including the Limited Use requirements. We use extension-derived information to provide or improve the disclosed job-application assistance purpose and related security and reliability functions. We do not sell it, use or transfer it for personalized advertising, transfer it to data brokers or information resellers, or use it to assess creditworthiness or for lending.</p></section>
        <section aria-labelledby="changes"><h2 id="changes">Changes and contact</h2><p>We may update this policy as the service changes. The date above identifies the current version. For privacy questions, contact <a className="ds-focus-ring rounded-control text-foreground-link underline underline-offset-4" href="mailto:privacy@xpertapply.com">privacy@xpertapply.com</a>.</p></section>
      </article>
    </main>
  );
}
